/**
 * Git Service (AG-10)
 * Handles branch creation, PR management, and GitHub API integration
 */

import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);

// GitHub repo configuration
const GITHUB_OWNER = process.env.GITHUB_OWNER || 'Othentic-Labs';
const GITHUB_REPO = process.env.GITHUB_REPO || 'ai-team';
const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
const DEFAULT_BASE_BRANCH = process.env.DEFAULT_BASE_BRANCH || 'master';

interface CreateBranchResult {
  success: boolean;
  branch?: string;
  error?: string;
}

interface CreatePRResult {
  success: boolean;
  prUrl?: string;
  prNumber?: number;
  error?: string;
}

interface PRInfo {
  number: number;
  state: 'open' | 'closed';
  merged: boolean;
  title: string;
  url: string;
}

export class GitService {
  private repoPath: string;

  constructor(repoPath?: string) {
    this.repoPath = repoPath || process.env.REPO_PATH || process.cwd();
  }

  /**
   * Generate a branch name from task ID and title
   * Pattern: task/{task-id}-{short-description}
   */
  generateBranchName(taskId: string, title: string): string {
    const slug = title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .substring(0, 30);
    return `task/${taskId}-${slug}`;
  }

  /**
   * Create a new branch for a task
   */
  async createBranch(taskId: string, title: string): Promise<CreateBranchResult> {
    const branchName = this.generateBranchName(taskId, title);

    try {
      // Fetch latest from origin
      await execAsync(`git fetch origin ${DEFAULT_BASE_BRANCH}`, { cwd: this.repoPath });

      // Create and checkout the new branch from base
      await execAsync(`git checkout -b ${branchName} origin/${DEFAULT_BASE_BRANCH}`, { cwd: this.repoPath });

      console.log(`[GitService] Created branch: ${branchName}`);
      return { success: true, branch: branchName };
    } catch (error) {
      const errorMsg = error instanceof Error ? error.message : String(error);
      console.error(`[GitService] Failed to create branch: ${errorMsg}`);

      // Check if branch already exists
      if (errorMsg.includes('already exists')) {
        try {
          await execAsync(`git checkout ${branchName}`, { cwd: this.repoPath });
          return { success: true, branch: branchName };
        } catch {
          return { success: false, error: `Branch exists but checkout failed: ${errorMsg}` };
        }
      }

      return { success: false, error: errorMsg };
    }
  }

  /**
   * Push branch to remote
   */
  async pushBranch(branchName: string): Promise<{ success: boolean; error?: string }> {
    try {
      await execAsync(`git push -u origin ${branchName}`, { cwd: this.repoPath });
      console.log(`[GitService] Pushed branch: ${branchName}`);
      return { success: true };
    } catch (error) {
      const errorMsg = error instanceof Error ? error.message : String(error);
      console.error(`[GitService] Failed to push branch: ${errorMsg}`);
      return { success: false, error: errorMsg };
    }
  }

  /**
   * Create a commit with task ID in message
   */
  async createCommit(taskId: string, message: string): Promise<{ success: boolean; error?: string }> {
    try {
      // Stage all changes
      await execAsync('git add -A', { cwd: this.repoPath });

      // Create commit with task ID prefix
      const commitMessage = `[${taskId}] ${message}`;
      await execAsync(`git commit -m "${commitMessage}"`, { cwd: this.repoPath });

      console.log(`[GitService] Created commit: ${commitMessage}`);
      return { success: true };
    } catch (error) {
      const errorMsg = error instanceof Error ? error.message : String(error);

      // "nothing to commit" is not really an error
      if (errorMsg.includes('nothing to commit')) {
        return { success: true };
      }

      console.error(`[GitService] Failed to create commit: ${errorMsg}`);
      return { success: false, error: errorMsg };
    }
  }

  /**
   * Create a Pull Request via GitHub API
   */
  async createPR(
    taskId: string,
    title: string,
    description: string,
    branchName: string
  ): Promise<CreatePRResult> {
    if (!GITHUB_TOKEN) {
      return { success: false, error: 'GITHUB_TOKEN not configured' };
    }

    try {
      // Push branch first
      const pushResult = await this.pushBranch(branchName);
      if (!pushResult.success) {
        return { success: false, error: pushResult.error };
      }

      // Create PR via GitHub API
      const prTitle = `[${taskId}] ${title}`;
      const prBody = `## Summary
${description}

## Task
- **ID:** ${taskId}
- **Title:** ${title}

## Changes
<!-- Auto-generated by agent -->

---
🤖 Generated by AI Agent`;

      const response = await fetch(`https://api.github.com/repos/${GITHUB_OWNER}/${GITHUB_REPO}/pulls`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${GITHUB_TOKEN}`,
          'Accept': 'application/vnd.github.v3+json',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          title: prTitle,
          body: prBody,
          head: branchName,
          base: DEFAULT_BASE_BRANCH,
        }),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        const errorMsg = (errorData as { message?: string }).message || `HTTP ${response.status}`;
        console.error(`[GitService] GitHub API error: ${errorMsg}`);
        return { success: false, error: errorMsg };
      }

      const data = await response.json() as { number: number; html_url: string };
      console.log(`[GitService] Created PR #${data.number}: ${data.html_url}`);

      return {
        success: true,
        prNumber: data.number,
        prUrl: data.html_url,
      };
    } catch (error) {
      const errorMsg = error instanceof Error ? error.message : String(error);
      console.error(`[GitService] Failed to create PR: ${errorMsg}`);
      return { success: false, error: errorMsg };
    }
  }

  /**
   * Get PR status from GitHub
   */
  async getPRStatus(prNumber: number): Promise<PRInfo | null> {
    if (!GITHUB_TOKEN) {
      return null;
    }

    try {
      const response = await fetch(
        `https://api.github.com/repos/${GITHUB_OWNER}/${GITHUB_REPO}/pulls/${prNumber}`,
        {
          headers: {
            'Authorization': `Bearer ${GITHUB_TOKEN}`,
            'Accept': 'application/vnd.github.v3+json',
          },
        }
      );

      if (!response.ok) {
        return null;
      }

      const data = await response.json() as {
        number: number;
        state: 'open' | 'closed';
        merged: boolean;
        title: string;
        html_url: string;
      };

      return {
        number: data.number,
        state: data.state,
        merged: data.merged,
        title: data.title,
        url: data.html_url,
      };
    } catch (error) {
      console.error(`[GitService] Failed to get PR status:`, error);
      return null;
    }
  }

  /**
   * Delete a branch (cleanup after merge)
   */
  async deleteBranch(branchName: string): Promise<{ success: boolean; error?: string }> {
    if (!GITHUB_TOKEN) {
      return { success: false, error: 'GITHUB_TOKEN not configured' };
    }

    try {
      // Delete remote branch
      const response = await fetch(
        `https://api.github.com/repos/${GITHUB_OWNER}/${GITHUB_REPO}/git/refs/heads/${branchName}`,
        {
          method: 'DELETE',
          headers: {
            'Authorization': `Bearer ${GITHUB_TOKEN}`,
            'Accept': 'application/vnd.github.v3+json',
          },
        }
      );

      if (!response.ok && response.status !== 404) {
        return { success: false, error: `HTTP ${response.status}` };
      }

      // Also try to delete local branch
      try {
        await execAsync(`git branch -D ${branchName}`, { cwd: this.repoPath });
      } catch {
        // Ignore local deletion errors
      }

      console.log(`[GitService] Deleted branch: ${branchName}`);
      return { success: true };
    } catch (error) {
      const errorMsg = error instanceof Error ? error.message : String(error);
      console.error(`[GitService] Failed to delete branch: ${errorMsg}`);
      return { success: false, error: errorMsg };
    }
  }

  /**
   * Get current branch name
   */
  async getCurrentBranch(): Promise<string | null> {
    try {
      const { stdout } = await execAsync('git rev-parse --abbrev-ref HEAD', { cwd: this.repoPath });
      return stdout.trim();
    } catch {
      return null;
    }
  }

  /**
   * Check if GitHub token is configured
   */
  isConfigured(): boolean {
    return !!GITHUB_TOKEN;
  }
}

export const gitService = new GitService();
